file = open("bucket_list.txt", "w")
file.write("1.Visit the Eiffel Tower\n")
file.write("2. Learn to Drive a BMW\n")
file.write("3. Drift the car\n")
file.close()
print("Bucket List saved to bucket-list.txt")

file = open("bucket_list.txt", "r")
content = file.read()
print("\n=== My Bucket List ===")
print(content)
file.close()

file = open("bucket_list.txt", "r")
lines = file.readlines()
print(f"You have {len(lines)} items in your bucket list.")
file.close()

file = open("bucket_list.txt", "a")
file.write("4. Go to Germany\n")
file.write("5. Drive a bugatti\n")
file.close()
print("\n2 more items added!")
file = open("bucket_list.txt", "r")
print("\n=== Updated Bucket List ===")
print(file.read())
file.close()